default: &default
  adapter: postgresql
  encoding: unicode
  username: minebixv2
  password: mbv2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minebixv2_development

test:
  <<: *default
  database: minebixv2_test

production:
  <<: *default
  database: minebixv2_production
